---
title: "Mortality dataset CA"
output: html_notebook
---

CA on the mortality dataset available on the FactoMineR package

```{r}
# load library
library(FactoMineR)
# load the data
data("mortality")
# inspect the dataset
mortality
```
As we can see, the dataset is a dataframe with 62 rows(the different causes of death) and 18 columns. Each columns represents an age interval.....

The first 9 cols correspond to data in 1979 and the 9 last columns correspond to data in 2006.

We will perform PCA considering only the data corresponding to 1979 (the first 9 columns)



Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Ctrl+Alt+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Ctrl+Shift+K* to preview the HTML file).

The preview shows you a rendered HTML copy of the contents of the editor. Consequently, unlike *Knit*, *Preview* does not run any R code chunks. Instead, the output of the chunk when it was last run in the editor is displayed.
